name: melody-auth-dev
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: melody-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    image: melody-auth-server:latest
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile.dev
    working_dir: /app/server
    env_file:
      - ../../server/.dev.vars
    ports:
      - "8787:8788"
    depends_on:
      - postgres
      - redis
    command: sh -c "sleep 5 && npm run node:migration:apply && npx vite --host --port 8788 --config vite-node.config.ts"

volumes:
  postgres_data:
  redis_data: